
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: argocd
resources:
  - tomcat.yaml
  - postgres.yaml
patches:
  - path: common.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
