kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tomcat-dev
spec:
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: tomcat
    targetRevision: 10.1.6
    helm:
      values: |
        tomcatUsername: manager 
        tomcatPassword: password
